### ISSUE TITLE
It says  Error: instead of C-style syntax, use D-style BYTE[1] tdData

### ISSUE THREAD

**Issue by kcvinker** [AndrejMitrovic/dtk#1]
Hi,
I just tried to run examples. All files are showing result message like this
" Error: instead of C-style syntax, use D-style BYTE[1] tdData."
What to do ? Do i need to change the code ?

**Comment by kcvinker** [comment]
After correcting that error, on next compilation, there are so many errors. I think this library is too old to use with current D lang standards.

**Comment by AndrejMitrovic** [comment]
Hi, I'm really sorry for the late reply. :)

I'm currently in the process of updating the library to work with the latest compilers. When it gets done, I'll make a comment here and resolve the issue.

In the meantime you could try checking out the alternative https://github.com/nomad-software/tkd

**Comment by AndrejMitrovic** [comment]
Resolved in v0.x.x.

However there's still a lot of work to do until this library is considered stable. I'll be putting my personal time into this project going forwards. Once the stable release is ready, I'll announce it in the D forums.
